### ISSUE TITLE
2) ¿Cómo funcionan las pantallas gigantes de matriz de puntos y cuáles son sus aplicaciones?

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea7-grupo-1#2]

**Comment by recursosssbb** [comment]
Times Square es famoso por sus brillantes y llamativas pantallas LED de matriz de puntos que muestran anuncios publicitarios, noticias en tiempo real, arte digital y contenido interactivo. Estas pantallas son una característica icónica de la plaza y atraen a millones de visitantes cada año.

Las pantallas de Times Square están compuestas por millas de pequeños módulos de LED dispuestos en una matriz de puntos. Cada módulo de LED es una pequeña luz que puede encenderse o apagarse individualmente, lo que permite mostrar una amplia variedad de contenido visual, desde anuncios publicitarios hasta transmisiones en vivo de eventos importantes. Estas pantallas gigantes se utilizan como un medio de publicidad y comunicación en uno de los lugares más concurridos del mundo.
