### ISSUE TITLE
3) Cómo funcionan las pantallas LCD y Oled gigantes y cuáles son sus aplicaciones?

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea7-grupo-1#3]

**Comment by recursosssbb** [comment]
Estas pantallas, a menudo conocidas como pantallas jumbotron o pantallas LED gigantes, se utilizan en estadios y arenas para mostrar repeticiones de jugadas, anuncios, estadísticas en tiempo real y otras imágenes relacionadas con el juego.

Estas pantallas gigantes ofrecen a los espectadores una experiencia inmersiva al permitirles ver detalles importantes y momentos destacados del juego desde diferentes ángulos. También se utilizan para mostrar publicidad, patrocinios y animaciones entretenidas.

**Comment by MariaBelen1** [comment]
se sube la tarea

**Comment by MariaBelen1** [comment]
se cierra la issue realizada
