### ISSUE TITLE
4) ¿Qué tecnología se podría utilizar para hacer una pantalla gigante táctil?. (SAW)

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea7-grupo-1#4]

**Comment by recursosssbb** [comment]
Una opción real y popular para crear una pantalla táctil gigante es la "Tecnología Capacitiva Proyectada" (PCT o PCAP).

La tecnología capacitiva proyectada es ampliamente utilizada en pantallas táctiles de gran tamaño, como las que se encuentran en quioscos interactivos, pantallas de señalización digital y paneles táctiles para presentaciones. Proporciona una respuesta táctil precisa y es capaz de manejar múltiples toques simultáneos. Además, es duradero y puede funcionar con vidrio grueso, lo que la hace adecuada para aplicaciones públicas o industriales.

Esta tecnología se basa en la detección de cambios en la capacitancia en la superficie de la pantalla cuando se toca con un dedo o un lápiz capacitivo. Al ser altamente sensible y confiable, la tecnología capacitiva proyectada es una opción sólida para pantallas táctiles gigantes.

**Comment by Maxg8704** [comment]
Agrego PDF Actividad 7-Ejercicio N°4 en carpeta ejercicios
