### ISSUE TITLE
5) ¿Cuál es la diferencia entre Oled SPI y Oled I2C?

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea7-grupo-1#5]

**Comment by recursosssbb** [comment]
[
![image](https://github.com/ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea7-grupo-1/assets/77708311/b53503b7-1f34-4934-a7f8-ec7a43bd2c5c)
](url)

**Comment by joseorsili** [comment]
PDF Cargado
