### ISSUE TITLE
7) Elija una aplicación (Wokwi, Proteus) con alguno de los visualizadores vistos e impleméntela con un simulador.

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea7-grupo-1#7]

**Comment by recursosssbb** [comment]
Para simular el uso de una pantalla Nextion y arduino - **NO ES POSIBLE USAR WOKWI.** para la simulacion  es posible que considerar otras opciones de software de simulación o, idealmente, probar el proyecto en un entorno de desarrollo real con una pantalla física Nextion y un Arduino. Las pantallas Nextion suelen ser utilizadas en proyectos de control de interfaces de usuario en tiempo real, y su simulación puede ser complicada en comparación con componentes electrónicos más simples.

**Comment by recursosssbb** [comment]
Pantalla Nextion y Arduino - Conexión Arduino Uno, Arduino Mega y Cambios en Librería           
                      https://www.youtube.com/watch?v=936R5zau0t4

**Comment by ulisesaale** [comment]
Subo dos ejemplos con distintos visualizadores para la tarea!! Ambas hechas en Wokwi
